services:
  redis:
    image: redis/redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"
    restart: unless-stopped
    networks:
      - rag_network

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    restart: unless-stopped
    networks:
      - rag_network

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "15672:15672"
      - "15691:15691"
      - "15692:15692"
      - "25672:25672"
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: unless-stopped
    networks:
      - rag_network

volumes:
  minio_data:

networks:
  rag_network:
    driver: bridge